changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels:
        - type: feature
    - title: Bug Fixes
      labels:
        - type: bug
    - title: CI and Tooling
      labels:
        - type: ci
    - title: Documentation
      labels:
        - type: docs
    - title: Refactoring
      labels:
        - type: refactor
    - title: Dependencies
      labels:
        - dependencies

